image: docker

#comment
services:
  - docker:dind

stages:
  - build
  
before_script:
  - docker login -u $docker_user -p $docker_key

build:
  stage: build
  script:
   - docker build -t myrepo .
   - docker push myrepo

